### ISSUE TITLE
please include MIT license text

### ISSUE THREAD

**Issue by decathorpe** [cecton/pure-rust-locales#1]
The terms of the MIT license require that the license text is included with the source code that it covers:
https://choosealicense.com/licenses/mit/

Please include the text of the MIT license (the usual name being either `LICENSE-MIT` in the case of dual-licensing, or in this case, just `LICENSE`).

**Comment by cecton** [comment]
Thanks, I completely forgot about that one.

I published 0.5.3 which holds the LICENSE

**Comment by decathorpe** [comment]
Thanks! :+1:
